# The base image
FROM greyhypotheses/greyhypotheses/aiu:spark_scala_3.5.0


# Within the greyhypotheses/aiu:spark_scala_3.5.0 base image beware of the settings
#
# Directories:
# WORKDIR /app
#
# Ports:
# SparkContext web UI on 4040 -- only available for the duration of the application.
# Spark master’s web UI on 8080.
# Spark worker web UI on 8081.
# EXPOSE 4040 8080 8081


# ENTRYPOINT
ENTRYPOINT ["bash"]