nodes:
  - name: determinands
    url: "https://environment.data.gov.uk/water-quality/def/determinands.csv"
    base: "determinands.csv"
    schema: "determinands.json"
  - name: samplingPointTypes
    url: "https://environment.data.gov.uk/water-quality/def/sampling-point-types.csv"
    base: "samplingPointTypes.csv"
    schema: "samplingPointTypes.json"
  - name: environmentAgencyArea
    url: "https://environment.data.gov.uk/water-quality/id/ea-area.csv"
    base: "environmentAgencyArea.csv"
    schema: "environmentAgencyArea.json"
  - name: environmentAgencySubarea
    url: "https://environment.data.gov.uk/water-quality/id/ea-subarea.csv"
    base: "environmentAgencySubarea.csv"
    schema: "environmentAgencySubarea.json"